#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=3 # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=off

# Setting up the general bar appearance and default values
sketchybar --bar     height=30											\
                     color=$BAR_COLOR									\
                     shadow=$SHADOW										\
                     position=top										\
                     border_width=2										\
                     border_color=$GREY									\
                     sticky=on											\
                     y_offset=8											\
                     padding_right=21									\
                     padding_left=21									\
                     corner_radius=15									\
                     margin=28											\
                     blur_radius=0										\
                     notch_width=0										\
                                                                        \
           --default updates=when_shown									\
                     icon.font="$FONT:Bold:14.0"						\
                     icon.color=$ICON_COLOR								\
                     icon.padding_left=$PADDINGS						\
                     icon.padding_right=$PADDINGS						\
                     label.font="$FONT:Semibold:13.0"					\
                     label.color=$LABEL_COLOR							\
                     label.padding_left=$PADDINGS						\
                     label.padding_right=$PADDINGS						\
                     background.padding_right=$PADDINGS					\
                     background.padding_left=$PADDINGS					\
                     popup.background.border_width=2					\
                     popup.background.corner_radius=11					\
                     popup.background.border_color=$POPUP_BORDER_COLOR	\
                     popup.background.color=$POPUP_BACKGROUND_COLOR		\
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/mpd.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/net.sh"
source "$ITEM_DIR/network.sh"

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
