#!/usr/bin/env sh

sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off # off/autoraise/
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0XFFD4D4D5
yabai -m config normal_window_border_color   0XFF3E4145
yabai -m config insert_feedback_color        0XFF37D99E
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config window_animation_duration    0.35

# general space settings
yabai -m config layout                       bsp
yabai -m config external_bar                 all:46:0
yabai -m config top_padding                  0
yabai -m config bottom_padding               28
yabai -m config left_padding                 28
yabai -m config right_padding                28
yabai -m config window_gap                   14

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^ProtonVPN$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Obsidian$" manage=off
yabai -m rule --add app="^Mos$" manage=off

# custom app launcher
yabai -m rule --add title="mylauncher" layer=above manage=off border=off

# turn off borders for these apps
yabai -m rule --add app="^VLC$" border=off
yabai -m rule --add app="^IINA$" border=off

# sketchybar
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

echo "yabai configuration loaded.."
