#!/usr/bin/env sh

# scripting addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
# yabai -m config window_border                on
# yabai -m config window_border_width          1
# yabai -m config active_window_border_color   0XFFD4D4D5
# yabai -m config normal_window_border_color   0XFF3E4145
yabai -m config insert_feedback_color        0XFF37D99E
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config window_animation_duration    0.35

# general space settings
yabai -m config layout                       bsp
yabai -m config external_bar                 all:28:0
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   8

# Set all windows sub-layer to below
yabai -m rule --add app=".*" sub-layer=below

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off sub-layer=below
yabai -m rule --add app="^Karabiner-Elements$" manage=off sub-layer=below
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off sub-layer=below
yabai -m rule --add app="^Finder$" manage=off sub-layer=below
yabai -m rule --add app="^Disk Utility$" manage=off sub-layer=below
yabai -m rule --add app="^System Information$" manage=off sub-layer=below
yabai -m rule --add app="^Activity Monitor$" manage=off sub-layer=below
yabai -m rule --add app="^Archive Utility$" manage=off sub-layer=below
yabai -m rule --add app="^Digital Colour Meter$" manage=off sub-layer=below
yabai -m rule --add app="^ProtonVPN$" manage=off sub-layer=below
yabai -m rule --add app="^Preview$" manage=off sub-layer=below
yabai -m rule --add app="^Obsidian$" manage=off sub-layer=below
yabai -m rule --add app="^Mos$" manage=off sub-layer=below
yabai -m rule --add app="^Notes$" manage=off sub-layer=below
yabai -m rule --add app="^Font Book$" manage=off sub-layer=below
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off sub-layer=below

# custom app launcher
yabai -m rule --add title="mylauncher" manage=off sub-layer=above

# keep pdf viewer in doc space
yabai -m rule --add app="^sioyek$" space=4

# sketchybar
yabai -m signal --add event=application_front_switched action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

echo "yabai configuration loaded.."
